### ISSUE TITLE
Loop when importing generated keys

### ISSUE THREAD

**Issue by pastinepolenta** [grassator/webpack-extract-translation-keys#11]
Hello, I might have misunderstood the point of this plugin. Maybe you can share some knowledge.
I am using it to extract all the strings from my app that need translation. But then I want to import those strings (`import trans from './translation-keys.json`) so that I can use them in React+Redux to send them to the backend and receive back the translated counterpart.

The extraction and the import works fine but I end up with a constant loop (in webpack dev server at least) where you can see webpack recompiling every second and the browser fetching the JSON file of the keys every second.

Is there a way to EXTRACT -> IMPORT -> USE without loops and repeat the loop only if a new string gets added or if a string gets modified ?

**Comment by grassator** [comment]
@stilllife00 My guess would be that you output translations into the same folder as the project itself. So when the translations file is output after the initial compilation, this re-triggers the cycle. Simple solution is to put the file outside of the folder webpack watches or specifically ignore this file [via a config option](https://webpack.js.org/configuration/watch/#watchoptions-ignored).
