### ISSUE TITLE
Webpack4 support

### ISSUE THREAD

**Issue by ViLPy** [grassator/webpack-extract-translation-keys#12]
Currently with Webpack4 we have  ```DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead``` on that line https://github.com/grassator/webpack-extract-translation-keys/blob/master/index.js#L43

Would it be possible to update that plugin to remove deprecation warnings?

**Comment by DeTeam** [comment]
@ViLPy let's fix it together?

I think it'd be a rather simple change :)
