### ISSUE TITLE
Empty translation file

### ISSUE THREAD

**Issue by pinkynrg** [grassator/webpack-extract-translation-keys#14]
I'm getting a file created but it's empty.

Here's how I'm using the plugin:

```
plugins: [
      new ExtractTranslationKeysPlugin({
          functionName: '_TR_',
          output: path.join(__dirname, 'translation-keys.json')
      }),
    ],
```

```
const _TR_ = function(a) {
  return a
}

_TR_('test')

let something = 'test2'

_TR_(something)
```

**Comment by grassator** [comment]
@pinkynrg Due to the way webpack works internally I was not able to make it work with local `__TR__` — it always has to be a global one wired in with `ProvidePlugin` as it is described in 
https://github.com/grassator/webpack-extract-translation-keys#runtime
