### ISSUE TITLE
Not getting variable added to file

### ISSUE THREAD

**Issue by pinkynrg** [grassator/webpack-extract-translation-keys#15]
I got to a point where ___tr___('something') adds "something" to the translation file.

On the other hand if I do ___tr___(some_variable) I won't get the value of some_variable in the list.

**Comment by grassator** [comment]
You actually should get an explicit error from Webpack if you try to use a variable. This plugin does static analysis of the code, so it can not know the value of the variable. This is by design, but I would be curious to understand your use case.

**Comment by pinkynrg** [comment]
I have several tag names coming from a third party software. I need to translate those because right now their value is like:

- this.is.variable[1]
- this.is.variable[2]
- this.is.variable[3]

Do you think this is a use case where I should manage the translations on the database?

**Comment by grassator** [comment]
The expected workaround for a case like this would be a switch:

```js
function tagToTranslation(tagName) {
  switch(tagName) {
    case "foo": return tr("my-foo-key")
    case "bar": return tr("my-bar-key")
  }
}
```

**Comment by grassator** [comment]
I'm closing this issue for now, please feel free to add more info though if you run into issues.
