### ISSUE TITLE
Incorrect key value order when key mangling option is set

### ISSUE THREAD

**Issue by laurismikals** [grassator/webpack-extract-translation-keys#17]
First of all thank you for the great plugin!

I think there is an issue with mangle option.
When key mangling is set, the output of the plugin is ` { "translation-key-1": " ", "translation-key-2": "!"}` - value first, key second - which reverse of what it should be.

In documentation it says that output should be ` {" ": "translation-key-1", "!": "translation-key-2"}` which is expected behavior.

Using "webpack": "^4.28.3", "webpack-extract-translation-keys-plugin": "^5.0.0",

**Comment by grassator** [comment]
@laurismikals sorry for the confusion, the README was actually incorrect, I've pushed the change.
