### ISSUE TITLE
compiler.parser is deprecated in webpack 2. 

### ISSUE THREAD

**Issue by vigneshshanmugam** [grassator/webpack-extract-translation-keys#3]

**Comment by grassator** [comment]
@vigneshshanmugam do you know if there is a suggested replacement for `compiler.parser`?

**Comment by vigneshshanmugam** [comment]
@grassator Sorry forgot to post the workaround. Here you go  https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.23
