### ISSUE TITLE
Is there a way to use this with i18n-webpack-plugin?

### ISSUE THREAD

**Issue by sidonaldson** [grassator/webpack-extract-translation-keys#5]
If i'm right in thinking this doesn't replace the content, it just builds the JSON file?

Can I use the replace function from i18n-webpack-plugin in combination with webpack-extract-translation-keys?

**Comment by grassator** [comment]
@sidonaldson Have you tried using these plugins together? If so, what is the result?

**Comment by sidonaldson** [comment]
@grassator thanks for the reply

i18n-webpack-plugin uses `__()` to replace the content and by default webpack-extract-translation-keys uses `_TR_()`.

I know I can change this so both plugins use `_TR_()` too.

```
new ExtractTranslationKeysPlugin({
    output: path.join(__dirname, 'translation-keys.json')
}),
new I18nPlugin(languages[language], {functionName: '_TR_', failOnMissing: true})
```

This method actually works, except the JSON file is empty. I think they both can't use the same function.

**Comment by grassator** [comment]
@sidonaldson I'm afraid not too deeply knowledgeable about webpack internals to be figure out what needs to be done to make it work, so I see a few options for you here:

1) Investigate this issue and provide a PR that will allow these plugins to coexist
2) Request / implement a feature to have a callback on each key inside I18nPlugin
3) Hack something around where you have to 2 separate builds—one gathering keys, the other actually replacing them.

**Comment by sidonaldson** [comment]
@grassator 3 is the most feasible. Thanks
