### ISSUE TITLE
Merge parsing results with existing file if possible

### ISSUE THREAD

**Issue by StephanBijzitter** [grassator/webpack-extract-translation-keys#6]
Right now, the plugin parses the source code for translation keys and outputs them as a newly written file at the provided location. This works very well.

However, I have an existing translation file with keys and translations already defined. Running this plugin would cause all translations to be overwritten. I would want the plugin to (optionally?) only add missing translation keys to the existing file, without overwriting the existing translations.

I would be willing to open a pull request for this if you can point me into the right direction. As it would be an optional additional feature, it can be released as a minor version.

**Comment by grassator** [comment]
Please see https://github.com/grassator/webpack-extract-translation-keys/pull/7#issuecomment-284512484
