### ISSUE TITLE
Move webpack to peerDependencies

### ISSUE THREAD

**Issue by alxmiron** [grassator/webpack-extract-translation-keys#9]
I think that since webpack is required inside the plugin itself, it should be moved from devDeps to peerDeps, like it's done [here](https://github.com/webpack-contrib/i18n-webpack-plugin/blob/master/package.json#L51). Am I right?

**Comment by grassator** [comment]
Yes, webpack should be a peer dependency, but *also* a dev one, as it is used in tests

**Comment by grassator** [comment]
Fixed now, thanks
